# Generated by Django 3.2.5 on 2021-09-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=10, verbose_name='grado')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('barrio', models.CharField(max_length=150, verbose_name='barrio')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('aceite_recolectado', models.IntegerField(default=0, verbose_name='aceite recolectado')),
                ('puntos', models.IntegerField(default=0, verbose_name='puntos de recoleccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
