# Generated by Django 3.2.6 on 2021-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='barrio',
            field=models.CharField(max_length=200, verbose_name='barrio'),
        ),
    ]
