# Generated by Django 3.2.5 on 2021-10-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucion_options'),
        ('estudiante', '0003_alter_estudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ni',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='numero_identificacion'),
        ),
    ]
