# Generated by Django 3.2.5 on 2021-09-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_proyecto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
