# Generated by Django 3.2.5 on 2021-10-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucion_options'),
        ('aceite', '0002_registro_aceite_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_aceite',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituciones.institucion'),
        ),
    ]
