# Generated by Django 3.2.5 on 2021-10-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestores',
            options={'verbose_name': 'Gestor', 'verbose_name_plural': 'Gestores'},
        ),
    ]
