# Generated by Django 3.2.6 on 2021-09-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name': 'Institucion', 'verbose_name_plural': 'Instituciones'},
        ),
    ]
