# Generated by Django 3.2.5 on 2021-10-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='aceite_recolectado',
            field=models.IntegerField(default=0),
        ),
    ]
