# Generated by Django 3.2.6 on 2021-10-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0003_institucion_aceite_recolectado'),
        ('estudiante', '0005_alter_estudiante_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('precio', models.BigIntegerField(verbose_name='precio')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'db_table': 'Premio',
            },
        ),
        migrations.CreateModel(
            name='PremiosEntregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_canjeo', models.CharField(max_length=8, verbose_name='codigo de canjeo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('premio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.premio')),
            ],
            options={
                'verbose_name': 'Premios Entregados',
                'verbose_name_plural': 'Premios Entregados',
                'db_table': 'PremiosEntregados',
            },
        ),
        migrations.AddField(
            model_name='premio',
            name='entregados',
            field=models.ManyToManyField(through='premios.PremiosEntregados', to='estudiante.Estudiante'),
        ),
        migrations.AddField(
            model_name='premio',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion'),
        ),
    ]
