# Generated by Django 3.2.5 on 2021-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0002_premio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiosentregados',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
